if (!require("devtools", quietly = TRUE))
    install.packages("devtools")
install.packages("RJSplot")
install.packages("XML")
install.packages("rgexf")
install.packages("tableHTML")
library(devtools)
install_github('Modesto-Escobar/rD3plot')
install_github('Modesto-Escobar/netCoin-2.x')
install_github('Modesto-Escobar/evolMap')